In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3]) + 4

array([5, 6, 7])

In [3]:
np.array([1, 2, 3]) + np.array([[4], [5], [6]])

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [4]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).sum(axis=0)

array([12, 15, 18])

In [6]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).sum(axis=1)

array([ 6, 15, 24])

In [7]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).sum()

45